### ISSUE TITLE
Check data_dir if not exists

### ISSUE THREAD

**Issue by mtchuyen** [secmask/mqueue#1]
If data_dir directory is not exist, the program has error:
error=open data/k2.mq: no such file or directory func=CompositeQueue#mapBackFile option={Name:k2 CacheSize:10485760 BackFile:data/k2.mq FileBlockUnit:2147483648}

**Comment by secmask** [comment]
this is designed, `data_dir` is expected to be existing and writable by `mqueue` at start. `mqueue` won't create it.
